import type {
  StudyAbroadConsultant,
  StudyAbroadCountry,
} from '@/features/study-abroad/types/study-abroad.types'

export const STUDY_ABROAD_COUNTRIES: {
  value: StudyAbroadCountry
  label: string
}[] = [
  { value: 'usa', label: 'USA' },
  { value: 'australia', label: 'Australia' },
  { value: 'canada', label: 'Canada' },
  { value: 'uk', label: 'UK' },
  { value: 'finland', label: 'Finland' },
  { value: 'austria', label: 'Austria' },
  { value: 'germany', label: 'Germany' },
]

export const STUDY_ABROAD_CONSULTANTS: StudyAbroadConsultant[] = [
  {
    id: 'kabita-humagain',
    name: 'Kabita Humagain',
    imageUrl: '/study-abroad/kabita.png',
    profileType: 'student',
    country: 'australia',
    city: 'Sydney',
    universityName: 'ACAP University College',
    services: ['Australia', 'Sydney', 'ACAP University College'],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'ayush-kc',
    name: 'Ayush KC',
    imageUrl: '/study-abroad/ayush.png',
    profileType: 'employee',
    country: 'australia',
    city: 'New Castle',
    position: 'Photographer',
    services: ['Australia', 'New Castle', 'Photographer'],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'sudeep-paudel',
    name: 'Sudeep Paudel',
    imageUrl: '/study-abroad/sudeep.png',
    profileType: 'employee',
    country: 'australia',
    city: 'Sydney',
    services: ['Australia', 'Sydney'],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'birat-k-c',
    name: 'Birat K C',
    imageUrl: '/study-abroad/birat.png',
    profileType: 'student',
    country: 'australia',
    city: 'Sydney',
    universityName: 'Charles Darwin University, Sydney Graduate',
    program: 'Masters in IT; CDU Student Leader',
    services: [
      'Australia',
      'Sydney',
      'Charles Darwin University',
      'Masters in IT',
      'CDU Student Leader',
    ],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'sabina-luitel',
    name: 'Sabina Luitel',
    imageUrl: '/study-abroad/sabina.png',
    profileType: 'student',
    country: 'australia',
    city: 'Tasmania',
    program:
      'Masters in Business Accounting; Masters in Professional Accounting; Diploma in Cookery and Hospitality',
    services: [
      'Australia',
      'Tasmania',
      'Masters in Business Accounting',
      'Masters in Professional Accounting',
      'Diploma in Cookery and Hospitality',
    ],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'sagar-pyakurel',
    name: 'Sagar Pyakurel',
    imageUrl: '/study-abroad/sagar.png',
    profileType: 'employee',
    country: 'australia',
    city: 'Tasmania',
    position: 'Overseer in Civil Engineering',
    services: ['Australia', 'Tasmania', 'Overseer in Civil Engineering'],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'ravi-shah',
    name: 'Ravi Shah',
    imageUrl: '/study-abroad/ravi.png',
    profileType: 'employee',
    country: 'canada',
    city: 'Brampton',
    services: ['Canada', 'Brampton'],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'arun-chauhan',
    name: 'Arun Chauhan',
    imageUrl: '/study-abroad/arun.png',
    profileType: 'student',
    country: 'australia',
    city: 'Sydney',
    universityName: 'University of Technology Sydney',
    services: ['Australia', 'South Australia', 'Sydney', 'University of Technology Sydney'],
    rating: 0,
    reviews: 0,
    totalSessions: 0,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
]
