import type {
  StudyAbroadConsultant,
  StudyAbroadCountry,
} from '@/features/study-abroad/types/study-abroad.types'

export const STUDY_ABROAD_COUNTRIES: {
  value: StudyAbroadCountry
  label: string
}[] = [
  { value: 'usa', label: 'USA' },
  { value: 'australia', label: 'Australia' },
  { value: 'canada', label: 'Canada' },
  { value: 'uk', label: 'UK' },
  { value: 'finland', label: 'Finland' },
  { value: 'austria', label: 'Austria' },
  { value: 'germany', label: 'Germany' },
]

export const STUDY_ABROAD_CONSULTANTS: StudyAbroadConsultant[] = [
  {
    id: 'maya-adhikari',
    name: 'Maya Adhikari',
    profileType: 'student',
    country: 'canada',
    city: 'Toronto',
    universityName: 'University of Toronto',
    program: 'MSc Computer Science',
    services: ['SOP review', 'Scholarships', 'Student life', 'Visa prep'],
    rating: 4.9,
    reviews: 38,
    totalSessions: 126,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2800 },
      { durationMinutes: 90, price: 4000 },
    ],
  },
  {
    id: 'aarav-sharma',
    name: 'Aarav Sharma',
    profileType: 'employee',
    country: 'usa',
    city: 'Seattle',
    position: 'Software Engineer',
    companyName: 'Microsoft',
    universityName: 'University of Washington',
    program: 'MS Computer Science',
    services: ['CS applications', 'Internships', 'Career planning', 'Interview prep'],
    rating: 4.8,
    reviews: 51,
    totalSessions: 183,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1800 },
      { durationMinutes: 60, price: 3400 },
      { durationMinutes: 90, price: 4800 },
    ],
  },
  {
    id: 'nisha-thapa',
    name: 'Nisha Thapa',
    profileType: 'student',
    country: 'uk',
    city: 'London',
    universityName: 'University College London',
    program: 'MA Education',
    services: ['UK applications', 'Personal statement', 'CAS process', 'Accommodation'],
    rating: 4.7,
    reviews: 29,
    totalSessions: 92,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1400 },
      { durationMinutes: 60, price: 2600 },
      { durationMinutes: 90, price: 3800 },
    ],
  },
  {
    id: 'sabin-kc',
    name: 'Sabin KC',
    profileType: 'employee',
    country: 'finland',
    city: 'Helsinki',
    position: 'Product Designer',
    companyName: 'Wolt',
    universityName: 'Aalto University',
    program: 'MA Collaborative and Industrial Design',
    services: ['Portfolio review', 'Nordic universities', 'Part-time work', 'Relocation'],
    rating: 4.9,
    reviews: 44,
    totalSessions: 117,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1600 },
      { durationMinutes: 60, price: 3000 },
      { durationMinutes: 90, price: 4300 },
    ],
  },
  {
    id: 'kritika-rai',
    name: 'Kritika Rai',
    profileType: 'student',
    country: 'australia',
    city: 'Melbourne',
    universityName: 'Monash University',
    program: 'Master of Business Analytics',
    services: ['GTE guidance', 'Course selection', 'Scholarships', 'Arrival checklist'],
    rating: 4.6,
    reviews: 24,
    totalSessions: 74,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1300 },
      { durationMinutes: 60, price: 2500 },
      { durationMinutes: 90, price: 3600 },
    ],
  },
  {
    id: 'bibek-poudel',
    name: 'Bibek Poudel',
    profileType: 'employee',
    country: 'germany',
    city: 'Berlin',
    position: 'Data Analyst',
    companyName: 'Zalando',
    universityName: 'Technical University of Munich',
    program: 'MSc Data Engineering and Analytics',
    services: ['Public universities', 'Blocked account', 'German job market', 'CV review'],
    rating: 4.8,
    reviews: 33,
    totalSessions: 105,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1500 },
      { durationMinutes: 60, price: 2900 },
      { durationMinutes: 90, price: 4200 },
    ],
  },
  {
    id: 'samjhana-gurung',
    name: 'Samjhana Gurung',
    profileType: 'student',
    country: 'austria',
    city: 'Vienna',
    universityName: 'University of Vienna',
    program: 'MSc International Business',
    services: ['Austria admissions', 'Document checklist', 'Visa interview', 'City settling'],
    rating: 4.7,
    reviews: 21,
    totalSessions: 68,
    verified: true,
    packages: [
      { durationMinutes: 30, price: 1200 },
      { durationMinutes: 60, price: 2300 },
      { durationMinutes: 90, price: 3400 },
    ],
  },
]
